# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PMSuperButton'
  # Pods for LoginApp

  target 'LoginAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
